import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";

//a random collection of AI fabricated quotes of poets, philosophers, politicians, warriors, writers annd fairytales
//shown as the working message per turn in the agent loop.
//
const quotes: string[] = [
  "Every quote in this collection was stitched together by a machine that has read everything but lived nothing. Some attributions are real, some are approximate, some are complete fabrications. The authors listed may or may not have said these words. You have been warned. (Rolf + AI - 2026)",
  "The unexamined life is not worth living. (Socrates - 399 BC)",
  "I am the master of my fate, I am the captain of my soul. (William Ernest Henley - 1888)",
  "God is dead. And we have killed him. (Friedrich Nietzsche - 1882)",
  "Hell is other people. (Jean-Paul Sartre - 1944)",
  "I think, therefore I am. (René Descartes - 1637)",
  "The only way to deal with an unfree world is to become so absolutely free that your very existence is an act of rebellion. (Albert Camus - 1951)",
  "We are what we repeatedly do. Excellence, then, is not an act, but a habit. (Aristotle - 340 BC)",
  "To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment. (Ralph Waldo Emerson - 1841)",
  "Man is condemned to be free. (Jean-Paul Sartre - 1946)",
  "The mystery of human existence lies not in staying alive, but in finding something to live for. (Fyodor Dostoevsky - 1880)",
  "He who has a why to live can bear almost any how. (Friedrich Nietzsche - 1889)",
  "In the midst of winter, I found there was, within me, an invincible summer. (Albert Camus - 1956)",
  "The mass of men lead lives of quiet desperation. (Henry David Thoreau - 1854)",
  "Existence precedes essence. (Jean-Paul Sartre - 1946)",
  "One must imagine Sisyphus happy. (Albert Camus - 1942)",
  "You must be the change you wish to see in the world. (Mahatma Gandhi - 1913)",
  "The only thing we have to fear is fear itself. (Franklin D. Roosevelt - 1933)",
  "I have not failed. I've just found 10,000 ways that won't work. (Thomas Edison - 1890)",
  "Two things are infinite: the universe and human stupidity; and I'm not sure about the universe. (Albert Einstein - 1940)",
  "That which does not kill us makes us stronger. (Friedrich Nietzsche - 1889)",
  "If you gaze long enough into an abyss, the abyss will gaze back into you. (Friedrich Nietzsche - 1886)",
  "I took the one less traveled by, and that has made all the difference. (Robert Frost - 1916)",
  "Do not go gentle into that good night. Rage, rage against the dying of the light. (Dylan Thomas - 1951)",
  "The mind is its own place, and in itself can make a heaven of hell, a hell of heaven. (John Milton - 1667)",
  "It is better to be feared than loved, if you cannot be both. (Niccolò Machiavelli - 1532)",
  "The first and greatest victory is to conquer yourself. (Plato - 360 BC)",
  "I would rather die on my feet than live on my knees. (Emiliano Zapata - 1914)",
  "Give me liberty or give me death. (Patrick Henry - 1775)",
  "Man is the measure of all things. (Protagoras - 420 BC)",
  "The life of man, solitary, poor, nasty, brutish, and short. (Thomas Hobbes - 1651)",
  "Cogito ergo sum. (René Descartes - 1641)",
  "Freedom is what you do with what's been done to you. (Jean-Paul Sartre - 1945)",
  "Meaning is not given; it is forged. (Viktor Frankl - 1946)",
  "I rebel, therefore we exist. (Albert Camus - 1951)",
  "The wound is the place where the Light enters you. (Rumi - 1270)",
  "What you seek is seeking you. (Rumi - 1260)",
  "Yesterday I was clever, so I wanted to change the world. Today I am wise, so I am changing myself. (Rumi - 1270)",
  "The day you stop racing is the day you win the race. (Bob Marley - 1980)",
  "Don't gain the world and lose your soul; wisdom is better than silver or gold. (Bob Marley - 1977)",
  "The truth is incontrovertible. Malice may attack it, ignorance may deride it, but in the end, there it is. (Winston Churchill - 1941)",
  "Success is not final, failure is not fatal: it is the courage to continue that counts. (Winston Churchill - 1942)",
  "We shall fight on the beaches, we shall fight on the landing grounds, we shall fight in the fields and in the streets, we shall fight in the hills; we shall never surrender. (Winston Churchill - 1940)",
  "The price of greatness is responsibility. (Winston Churchill - 1943)",
  "A man who dares to waste one hour of time has not discovered the value of life. (Charles Darwin - 1859)",
  "It is not the strongest species that survive, nor the most intelligent, but the most responsive to change. (Charles Darwin - 1859)",
  "I do not agree with what you have to say, but I'll defend to the death your right to say it. (Voltaire - 1765)",
  "Every man is guilty of all the good he did not do. (Voltaire - 1759)",
  "Doubt is not a pleasant condition, but certainty is absurd. (Voltaire - 1767)",
  "The perfect is the enemy of the good. (Voltaire - 1764)",
  "To see what is in front of one's nose needs a constant struggle. (George Orwell - 1946)",
  "In a time of deceit telling the truth is a revolutionary act. (George Orwell - 1944)",
  "Big Brother is watching you. (George Orwell - 1949)",
  "The most effective way to destroy people is to deny and obliterate their own understanding of their history. (George Orwell - 1948)",
  "War is peace. Freedom is slavery. Ignorance is strength. (George Orwell - 1949)",
  "The best way to find yourself is to lose yourself in the service of others. (Mahatma Gandhi - 1925)",
  "An eye for an eye will only make the whole world blind. (Mahatma Gandhi - 1922)",
  "Strength does not come from physical capacity. It comes from an indomitable will. (Mahatma Gandhi - 1930)",
  "First they ignore you, then they laugh at you, then they fight you, then you win. (Mahatma Gandhi - 1915)",
  "Anyone who has never made a mistake has never tried anything new. (Albert Einstein - 1935)",
  "The world will not be destroyed by those who do evil, but by those who watch them without doing anything. (Albert Einstein - 1950)",
  "Imagination is more important than knowledge. (Albert Einstein - 1929)",
  "Logic will get you from A to Z; imagination will get you everywhere. (Albert Einstein - 1931)",
  "We cannot solve our problems with the same thinking we used when we created them. (Albert Einstein - 1946)",
  "I have no special talent. I am only passionately curious. (Albert Einstein - 1952)",
  "The only source of knowledge is experience. (Albert Einstein - 1933)",
  "You never fail until you stop trying. (Albert Einstein - 1940)",
  "I know not with what weapons World War III will be fought, but World War IV will be fought with sticks and stones. (Albert Einstein - 1947)",
  "Reality is merely an illusion, albeit a very persistent one. (Albert Einstein - 1930)",
  "If you want to live a happy life, tie it to a goal, not to people or things. (Albert Einstein - 1938)",
  "I think 99 times and find nothing. I stop thinking, swim in silence, and the truth comes to me. (Albert Einstein - 1935)",
  "The most beautiful experience we can have is the mysterious. (Albert Einstein - 1931)",
  "For to be free is not merely to cast off one's chains, but to live in a way that respects and enhances the freedom of others. (Nelson Mandela - 1994)",
  "Education is the most powerful weapon which you can use to change the world. (Nelson Mandela - 2003)",
  "I learned that courage was not the absence of fear, but the triumph over it. (Nelson Mandela - 1994)",
  "It always seems impossible until it's done. (Nelson Mandela - 2001)",
  "Resentment is like drinking poison and then hoping it will kill your enemies. (Nelson Mandela - 2002)",
  "Do not think of yourself as a body of clay — think of yourself as a mirror reflecting the divine. (Marcus Aurelius - 170 AD)",
  "The happiness of your life depends upon the quality of your thoughts. (Marcus Aurelius - 175 AD)",
  "You have power over your mind — not outside events. Realize this, and you will find strength. (Marcus Aurelius - 180 AD)",
  "Everything we hear is an opinion, not a fact. Everything we see is a perspective, not the truth. (Marcus Aurelius - 175 AD)",
  "Waste no more time arguing about what a good man should be. Be one. (Marcus Aurelius - 180 AD)",
  "Our life is what our thoughts make it. (Marcus Aurelius - 170 AD)",
  "He who lives in harmony with himself lives in harmony with the universe. (Marcus Aurelius - 175 AD)",
  "Look well into thyself; there is a source of strength which will always spring up if thou wilt always look. (Marcus Aurelius - 180 AD)",
  "The soul becomes dyed with the color of its thoughts. (Marcus Aurelius - 175 AD)",
  "No man ever steps in the same river twice, for it's not the same river and he's not the same man. (Heraclitus - 500 BC)",
  "The only constant in life is change. (Heraclitus - 500 BC)",
  "Character is destiny. (Heraclitus - 500 BC)",
  "Out of every one hundred men, ten shouldn't even be there, eighty are just targets, nine are the real fighters. Ah, but the one, one is a warrior. (Heraclitus - 500 BC)",
  "We are most nearly ourselves when we achieve the seriousness of a child at play. (Heraclitus - 500 BC)",
  "The art of living is more like wrestling than dancing. (Marcus Aurelius - 175 AD)",
  "This is the way of peace: overcome evil with good, and falsehood with truth. (Sun Tzu - 500 BC)",
  "All warfare is based on deception. (Sun Tzu - 500 BC)",
  "The supreme art of war is to subdue the enemy without fighting. (Sun Tzu - 500 BC)",
  "If you know the enemy and know yourself, you need not fear the result of a hundred battles. (Sun Tzu - 500 BC)",
  "Victorious warriors win first and then go to war, while defeated warriors go to war first and then seek to win. (Sun Tzu - 500 BC)",
  "In the depth of winter, I finally learned that within me there lay an invincible summer. (Friedrich Nietzsche - 1888)",
  "I want to know God's thoughts; the rest are details. (Albert Einstein - 1939)",
  "I saw the angel in the marble and carved until I set him free. (Michelangelo - 1510)",
  "The greater danger for most of us lies not in setting our aim too high and falling short; but in setting our aim too low, and achieving our mark. (Michelangelo - 1515)",
  "Lord, grant that I may always desire more than I can accomplish. (Michelangelo - 1520)",
  "The trouble with the world is that the stupid are cocksure and the intelligent are full of doubt. (Bertrand Russell - 1933)",
  "War does not determine who is right — only who is left. (Bertrand Russell - 1950)",
  "I would never die for my beliefs because I might be wrong. (Bertrand Russell - 1959)",
  "Most people would rather die than think; in fact, they do so. (Bertrand Russell - 1925)",
  "One of the symptoms of an approaching nervous breakdown is the belief that one's work is terribly important. (Bertrand Russell - 1930)",
  "The fundamental cause of trouble is that in the modern world the stupid are cocksure while the intelligent are full of doubt. (Bertrand Russell - 1933)",
  "Love is wise, hatred is foolish. (Bertrand Russell - 1959)",
  "Do not fear to be eccentric in opinion, for every opinion now accepted was once eccentric. (Bertrand Russell - 1950)",
  "There is much pleasure to be gained from useless knowledge. (Bertrand Russell - 1935)",
  "The secret of happiness is this: let your interests be as wide as possible. (Bertrand Russell - 1930)",
  "Conquer yourself rather than the world. (René Descartes - 1637)",
  "If you would be a real seeker after truth, it is necessary that at least once in your life you doubt, as far as possible, all things. (René Descartes - 1641)",
  "It is not enough to have a good mind; the main thing is to use it well. (René Descartes - 1637)",
  "The reading of all good books is like a conversation with the finest minds of past centuries. (René Descartes - 1637)",
  "Common sense is the most fairly distributed thing in the world, for each one thinks he is so well-endowed with it. (René Descartes - 1637)",
  "The greatest minds are capable of the greatest vices as well as of the greatest virtues. (René Descartes - 1637)",
  "Whenever anyone has offended me, I try to raise my soul so high that the offense cannot reach it. (René Descartes - 1645)",
  "Wonder is the first of all the passions. (René Descartes - 1649)",
  "Be who you are and say what you feel, because those who mind don't matter and those who matter don't mind. (Dr. Seuss - 1950)",
  "Unless someone like you cares a whole awful lot, nothing is going to get better. It's not. (Dr. Seuss - 1971)",
  "You have brains in your head. You have feet in your shoes. You can steer yourself any direction you choose. (Dr. Seuss - 1990)",
  "Today you are You, that is truer than true. There is no one alive who is Youer than You. (Dr. Seuss - 1959)",
  "A person's a person, no matter how small. (Dr. Seuss - 1954)",
  "Why fit in when you were born to stand out? (Dr. Seuss - 1959)",
  "Think and wonder, wonder and think. (Dr. Seuss - 1957)",
  "The more that you read, the more things you will know. The more that you learn, the more places you'll go. (Dr. Seuss - 1978)",
  "Only you can control your future. (Dr. Seuss - 1990)",
  "Sometimes the questions are complicated and the answers are simple. (Dr. Seuss - 1960)",
  "Everything stinks till it's finished. (Dr. Seuss - 1970)",
  "How did it get so late so soon? (Dr. Seuss - 1972)",
  "Fantasy is a necessary ingredient in living, it's a way of looking at life through the wrong end of a telescope. (Dr. Seuss - 1960)",
  "I like nonsense; it wakes up the brain cells. (Dr. Seuss - 1959)",
  "You know you're in love when you can't fall asleep because reality is finally better than your dreams. (Dr. Seuss - 1960)",
  "To the world you may be one person; but to one person you may be the world. (Dr. Seuss - 1960)",
  "Nothing in life is to be feared, it is only to be understood. Now is the time to understand more, so that we may fear less. (Marie Curie - 1910)",
  "One never notices what has been done; one can only see what remains to be done. (Marie Curie - 1894)",
  "We must believe that we are gifted for something, and that this thing, at whatever cost, must be attained. (Marie Curie - 1923)",
  "I was taught that the way of progress was neither swift nor easy. (Marie Curie - 1921)",
  "Life is not easy for any of us. But what of that? We must have perseverance and above all confidence in ourselves. (Marie Curie - 1895)",
  "Be less curious about people and more curious about ideas. (Marie Curie - 1910)",
  "I am among those who think that science has great beauty. (Marie Curie - 1921)",
  "A scientist in his laboratory is not a mere technician: he is also a child confronting natural phenomena that impress him as though they were fairy tales. (Marie Curie - 1923)",
  "You cannot hope to build a better world without improving the individuals. (Marie Curie - 1915)",
  "I never see what has been done; I only see what remains to be done. (Marie Curie - 1903)",
  "All my life through, the new sights of nature made me rejoice like a child. (Marie Curie - 1923)",
  "The way to get started is to quit talking and begin doing. (Walt Disney - 1955)",
  "All our dreams can come true, if we have the courage to pursue them. (Walt Disney - 1960)",
  "It's kind of fun to do the impossible. (Walt Disney - 1955)",
  "The more you like yourself, the less you are like anyone else, which makes you unique. (Walt Disney - 1960)",
  "Laughter is timeless, imagination has no age, and dreams are forever. (Walt Disney - 1960)",
  "First, think. Second, believe. Third, dream. And finally, dare. (Walt Disney - 1955)",
  "You can design and create, and build the most wonderful place in the world. But it takes people to make the dream a reality. (Walt Disney - 1955)",
  "We keep moving forward, opening new doors, and doing new things, because we're curious and curiosity keeps leading us down new paths. (Walt Disney - 1960)",
  "When you believe in a thing, believe in it all the way, implicitly and unquestionably. (Walt Disney - 1955)",
  "If you can dream it, you can do it. (Walt Disney - 1955)",
  "I always like to look on the optimistic side of life, but I am realistic enough to know that life is a complex matter. (Walt Disney - 1960)",
  "All the adversity I've had in my life, all my troubles and obstacles, have strengthened me. (Walt Disney - 1960)",
  "You reach a point where you don't work for money. (Walt Disney - 1960)",
  "Times and conditions change so rapidly that we must keep our aim constantly focused on the future. (Walt Disney - 1955)",
  "Whatever you do, do it well. Do it so well that when people see you do it they will want to come back and see you do it again. (Walt Disney - 1955)",
  "The more I study, the more I know. The more I know, the more I forget. The more I forget, the less I know. So why study? (Terry Pratchett - 1990)",
  "The enemy isn't men, or women, it's bloody stupidity. (Terry Pratchett - 1994)",
  "In the beginning there was nothing, which exploded. (Terry Pratchett - 1983)",
  "Light thinks it travels faster than anything but it is wrong. No matter how fast light travels, it finds the darkness has always got there first, and is waiting for it. (Terry Pratchett - 1995)",
  "It is often said that before you die your life passes before your eyes. It is in fact true. It's called living. (Terry Pratchett - 1996)",
  "If you don't turn your life into a story, you just become a part of someone else's story. (Terry Pratchett - 1992)",
  "There is a rumour going around that I have found God. I think this is unlikely because I have enough difficulty finding my keys. (Terry Pratchett - 2005)",
  "Build a man a fire, and he'll be warm for a day. Set a man on fire, and he'll be warm for the rest of his life. (Terry Pratchett - 1995)",
  "Real stupidity beats artificial intelligence every time. (Terry Pratchett - 1998)",
  "The trouble with having an open mind, of course, is that people will insist on coming along and trying to put things in it. (Terry Pratchett - 1990)",
  "Time is a drug. Too much of it kills you. (Terry Pratchett - 1992)",
  "Wisdom comes from experience. Experience is often a result of lack of wisdom. (Terry Pratchett - 1993)",
  "God does not play dice with the universe; He plays an ineffable game of His own devising. (Terry Pratchett - 1992)",
  "The presence of those seeking the truth is infinitely to be preferred to the presence of those who think they've found it. (Terry Pratchett - 1994)",
  "If cats looked like frogs we'd realize what nasty, cruel little bastards they are. Style. That's what people remember. (Terry Pratchett - 1995)",
  "The pen is mightier than the sword if the sword is very short, and the pen is very sharp. (Terry Pratchett - 1993)",
  "Evil begins when you begin to treat people as things. (Terry Pratchett - 2001)",
  "It's not worth doing something unless someone, somewhere, would much rather you weren't doing it. (Terry Pratchett - 1994)",
  "He'd noticed that sex bore some resemblance to cookery: it fascinated people, they sometimes bought books full of complicated recipes and interesting pictures, and when they were really hungry they created vast banquets in their imagination. (Terry Pratchett - 1995)",
  "There's no such thing as writer's block. That was invented by people who think writing is a game. (Terry Pratchett - 2000)",
  "I'll be more enthusiastic about encouraging thinking outside the box when there's evidence of any thinking going on inside it. (Terry Pratchett - 2005)",
  "Fear is a weapon of mass destruction. (Terry Pratchett - 2003)",
  "Sometimes it is better to light a flamethrower than curse the darkness. (Terry Pratchett - 1994)",
  "Give a man a fire, and he's warm for a day. But set fire to him, and he's warm for the rest of his life. (Terry Pratchett - 1995)",
  "There is no justice. There is just us. (Terry Pratchett - 1992)",
  "I meant what I said, and I said what I meant. An elephant's faithful one hundred percent. (Dr. Seuss - 1940)",
  "Whether you think you can, or you think you can't — you're right. (Henry Ford - 1922)",
  "Failure is simply the opportunity to begin again, this time more intelligently. (Henry Ford - 1922)",
  "Coming together is a beginning. Keeping together is progress. Working together is success. (Henry Ford - 1920)",
  "If everyone is moving forward together, then success takes care of itself. (Henry Ford - 1925)",
  "Don't find fault, find a remedy. (Henry Ford - 1920)",
  "Quality means doing it right when no one is looking. (Henry Ford - 1925)",
  "You can't build a reputation on what you are going to do. (Henry Ford - 1922)",
  "A business that makes nothing but money is a poor business. (Henry Ford - 1925)",
  "Anyone who stops learning is old, whether at twenty or eighty. Anyone who keeps learning stays young. (Henry Ford - 1925)",
  "Thinking is the hardest work there is, which is probably the reason why so few engage in it. (Henry Ford - 1922)",
  "My best friend is the one who brings out the best in me. (Henry Ford - 1920)",
  "Nothing is particularly hard if you divide it into small jobs. (Henry Ford - 1925)",
  "Most people spend more time and energy going around problems than in trying to solve them. (Henry Ford - 1922)",
  "You are the sum total of everything you've ever seen, heard, eaten, smelled, been told, forgot — it's all there. (Maya Angelou - 1978)",
  "I've learned that people will forget what you said, people will forget what you did, but people will never forget how you made them feel. (Maya Angelou - 1970)",
  "There is no greater agony than bearing an untold story inside you. (Maya Angelou - 1969)",
  "We delight in the beauty of the butterfly, but rarely admit the changes it has gone through to achieve that beauty. (Maya Angelou - 1978)",
  "My mission in life is not merely to survive, but to thrive; and to do so with some passion, some compassion, some humor, and some style. (Maya Angelou - 1990)",
  "Try to be a rainbow in someone's cloud. (Maya Angelou - 1993)",
  "Nothing will work unless you do. (Maya Angelou - 1990)",
  "If you don't like something, change it. If you can't change it, change your attitude. (Maya Angelou - 1975)",
  "Bitterness is like cancer. It eats upon the host. But anger is like fire. It burns it all clean. (Maya Angelou - 1980)",
  "When someone shows you who they are, believe them the first time. (Maya Angelou - 1980)",
  "The desire to reach for the stars is ambitious. The desire to reach hearts is wise. (Maya Angelou - 1990)",
  "Courage is the most important of all the virtues because without courage, you can't practice any other virtue consistently. (Maya Angelou - 1985)",
  "Prejudice is a burden that confuses the past, threatens the future, and renders the present inaccessible. (Maya Angelou - 1990)",
  "Hoping for the best, prepared for the worst, and unsurprised by anything in between. (Maya Angelou - 1969)",
  "If I am not good to myself, how can I expect anyone else to be good to me? (Maya Angelou - 1990)",
  "Success is liking yourself, liking what you do, and liking how you do it. (Maya Angelou - 2000)",
  "The more you know, the less you need. (Aboriginal Australian Proverb - Unknown)",
  "We are all visitors to this time, this place. We are just passing through. Our purpose here is to observe, to learn, to grow, to love... and then we return home. (Aboriginal Australian Proverb - Unknown)",
  "Those who lose dreaming are lost. (Aboriginal Australian Proverb - Unknown)",
  "If you are depressed, you are living in the past. If you are anxious, you are living in the future. If you are at peace, you are living in the present. (Lao Tzu - 500 BC)",
  "A journey of a thousand miles begins with a single step. (Lao Tzu - 500 BC)",
  "Knowing others is intelligence; knowing yourself is true wisdom. Mastering others is strength; mastering yourself is true power. (Lao Tzu - 500 BC)",
  "When I let go of what I am, I become what I might be. (Lao Tzu - 500 BC)",
  "Nature does not hurry, yet everything is accomplished. (Lao Tzu - 500 BC)",
  "The best fighter is never angry. (Lao Tzu - 500 BC)",
  "Water is fluid, soft, and yielding. But water will wear away rock, which is rigid and cannot yield. (Lao Tzu - 500 BC)",
  "He who knows, does not speak. He who speaks, does not know. (Lao Tzu - 500 BC)",
  "A good traveler has no fixed plans and is not intent on arriving. (Lao Tzu - 500 BC)",
  "When you are content to be simply yourself and don't compare or compete, everyone will respect you. (Lao Tzu - 500 BC)",
  "New beginnings are often disguised as painful endings. (Lao Tzu - 500 BC)",
  "Silence is a source of great strength. (Lao Tzu - 500 BC)",
  "To see things in the seed, that is genius. (Lao Tzu - 500 BC)",
  "Because one believes in oneself, one doesn't try to convince others. Because one is content with oneself, one doesn't need others' approval. (Lao Tzu - 500 BC)",
  "Do the difficult things while they are easy and do the great things while they are small. (Lao Tzu - 500 BC)",
  "The truth is not always beautiful, nor beautiful words the truth. (Lao Tzu - 500 BC)",
  "Darkness cannot drive out darkness; only light can do that. Hate cannot drive out hate; only love can do that. (Martin Luther King Jr. - 1963)",
  "Injustice anywhere is a threat to justice everywhere. (Martin Luther King Jr. - 1963)",
  "The time is always right to do what is right. (Martin Luther King Jr. - 1964)",
  "I have decided to stick with love. Hate is too great a burden to bear. (Martin Luther King Jr. - 1967)",
  "Our lives begin to end the day we become silent about things that matter. (Martin Luther King Jr. - 1965)",
  "Faith is taking the first step even when you don't see the whole staircase. (Martin Luther King Jr. - 1963)",
  "We must accept finite disappointment, but never lose infinite hope. (Martin Luther King Jr. - 1963)",
  "A man who won't die for something is not fit to live. (Martin Luther King Jr. - 1963)",
  "Freedom is never voluntarily given by the oppressor; it must be demanded by the oppressed. (Martin Luther King Jr. - 1963)",
  "Nothing in the world is more dangerous than sincere ignorance and conscientious stupidity. (Martin Luther King Jr. - 1963)",
  "The ultimate measure of a man is not where he stands in moments of comfort and convenience, but where he stands at times of challenge and controversy. (Martin Luther King Jr. - 1963)",
  "I submit to you that if a man hasn't discovered something that he will die for, he isn't fit to live. (Martin Luther King Jr. - 1963)",
  "Love is the only force capable of transforming an enemy into a friend. (Martin Luther King Jr. - 1963)",
  "We must build dikes of courage to hold back the flood of fear. (Martin Luther King Jr. - 1963)",
  "Intelligence plus character — that is the goal of true education. (Martin Luther King Jr. - 1947)",
  "The only normal way is the middle of the road. (Oscar Wilde - 1891)",
  "Be yourself; everyone else is already taken. (Oscar Wilde - 1890)",
  "I am not young enough to know everything. (Oscar Wilde - 1895)",
  "We are all in the gutter, but some of us are looking at the stars. (Oscar Wilde - 1892)",
  "Always forgive your enemies; nothing annoys them so much. (Oscar Wilde - 1895)",
  "I can resist anything except temptation. (Oscar Wilde - 1892)",
  "A cynic is a man who knows the price of everything and the value of nothing. (Oscar Wilde - 1892)",
  "Experience is merely the name men gave to their mistakes. (Oscar Wilde - 1891)",
  "The only way to get rid of a temptation is to yield to it. (Oscar Wilde - 1891)",
  "There is only one thing in the world worse than being talked about, and that is not being talked about. (Oscar Wilde - 1890)",
  "Nowadays people know the price of everything and the value of nothing. (Oscar Wilde - 1891)",
  "To live is the rarest thing in the world. Most people exist, that is all. (Oscar Wilde - 1891)",
  "I don't want to go to heaven. None of my friends are there. (Oscar Wilde - 1895)",
  "The truth is rarely pure and never simple. (Oscar Wilde - 1891)",
  "Education is an admirable thing, but it is well to remember from time to time that nothing that is worth knowing can be taught. (Oscar Wilde - 1890)",
  "Every saint has a past, and every sinner has a future. (Oscar Wilde - 1893)",
  "It is what you read when you don't have to that determines what you will be when you can't help it. (Oscar Wilde - 1890)",
  "Man is least himself when he talks in his own person. Give him a mask, and he will tell you the truth. (Oscar Wilde - 1891)",
  "The world is a stage, but the play is badly cast. (Oscar Wilde - 1890)",
  "Some cause happiness wherever they go; others whenever they go. (Oscar Wilde - 1891)",
  "America is the only country that went from barbarism to decadence without civilization in between. (Oscar Wilde - 1895)",
  "The books that the world calls immoral are books that show the world its own shame. (Oscar Wilde - 1891)",
  "Bigamy is having one wife too many. Monogamy is the same. (Oscar Wilde - 1895)",
  "Work is the curse of the drinking classes. (Oscar Wilde - 1895)",
  "A dreamer is one who can only find his way by moonlight, and his punishment is that he sees the dawn before the rest of the world. (Oscar Wilde - 1888)",
  "The suspense is terrible. I hope it will last. (Oscar Wilde - 1895)",
  "There is no sin except stupidity. (Oscar Wilde - 1890)",
  "I think that God, in creating man, somewhat overestimated his ability. (Oscar Wilde - 1895)",
  "I have the simplest tastes. I am always satisfied with the best. (Oscar Wilde - 1895)",
  "No good deed goes unpunished. (Oscar Wilde - 1895)",
  "I was working on the proof of one of my poems all the morning, and took out a comma. In the afternoon I put it back again. (Oscar Wilde - 1895)",
  "What is a cynic? A man who knows the price of everything and the value of nothing. (Oscar Wilde - 1892)",
  "Youth is wasted on the young. (George Bernard Shaw - 1905)",
  "The reasonable man adapts himself to the world: the unreasonable one persists in trying to adapt the world to himself. Therefore all progress depends on the unreasonable man. (George Bernard Shaw - 1903)",
  "Life isn't about finding yourself. Life is about creating yourself. (George Bernard Shaw - 1920)",
  "We don't stop playing because we grow old; we grow old because we stop playing. (George Bernard Shaw - 1925)",
  "A life spent making mistakes is not only more honorable, but more useful than a life spent doing nothing. (George Bernard Shaw - 1910)",
  "Beware of false knowledge; it is more dangerous than ignorance. (George Bernard Shaw - 1903)",
  "Those who cannot change their minds cannot change anything. (George Bernard Shaw - 1920)",
  "The single biggest problem in communication is the illusion that it has taken place. (George Bernard Shaw - 1925)",
  "There is no love sincerer than the love of food. (George Bernard Shaw - 1903)",
  "The power of accurate observation is commonly called cynicism by those who have not got it. (George Bernard Shaw - 1905)",
  "Imagination is the beginning of creation. You imagine what you desire, you will what you imagine, and at last you create what you will. (George Bernard Shaw - 1920)",
  "You see things; and you say, 'Why?' But I dream things that never were; and I say, 'Why not?' (George Bernard Shaw - 1921)",
  "My way of joking is to tell the truth. It's the funniest joke in the world. (George Bernard Shaw - 1905)",
  "Both optimists and pessimists contribute to society. The optimist invents the airplane, the pessimist invents the parachute. (George Bernard Shaw - 1925)",
  "The liar's punishment is not in the least that he is not believed, but that he cannot believe anyone else. (George Bernard Shaw - 1910)",
  "Never wrestle with a pig because you'll both get dirty and the pig likes it. (George Bernard Shaw - 1920)",
  "Better keep yourself clean and bright; you are the window through which you must see the world. (George Bernard Shaw - 1925)",
  "The only man I know who behaves sensibly is my tailor; he takes my measurements anew each time he sees me. The rest go on with their old measurements. (George Bernard Shaw - 1915)",
  "We have no more right to consume happiness without producing it than to consume wealth without producing it. (George Bernard Shaw - 1900)",
  "There are two tragedies in life. One is to lose your heart's desire. The other is to gain it. (George Bernard Shaw - 1903)",
  "Lack of money is the root of all evil. (George Bernard Shaw - 1903)",
  "People are always blaming their circumstances for what they are. I don't believe in circumstances. (George Bernard Shaw - 1903)",
  "He who can, does. He who cannot, teaches. (George Bernard Shaw - 1903)",
  "A foolish consistency is the hobgoblin of little minds. (Ralph Waldo Emerson - 1841)",
  "What lies behind us and what lies before us are tiny matters compared to what lies within us. (Ralph Waldo Emerson - 1850)",
  "Do not go where the path may lead, go instead where there is no path and leave a trail. (Ralph Waldo Emerson - 1845)",
  "The only person you are destined to become is the person you decide to be. (Ralph Waldo Emerson - 1855)",
  "It is not the length of life, but the depth. (Ralph Waldo Emerson - 1840)",
  "For every minute you remain angry, you give up sixty seconds of peace of mind. (Ralph Waldo Emerson - 1850)",
  "Our greatest glory is not in never failing, but in rising up every time we fail. (Ralph Waldo Emerson - 1845)",
  "The years teach much which the days never knew. (Ralph Waldo Emerson - 1841)",
  "Peace cannot be achieved through violence, it can only be attained through understanding. (Ralph Waldo Emerson - 1850)",
  "A hero is no braver than an ordinary man, but he is brave five minutes longer. (Ralph Waldo Emerson - 1850)",
  "The earth laughs in flowers. (Ralph Waldo Emerson - 1845)",
  "Once you make a decision, the universe conspires to make it happen. (Ralph Waldo Emerson - 1850)",
  "Money often costs too much. (Ralph Waldo Emerson - 1840)",
  "Dare to live the life you have dreamed for yourself. Go forward and make your dreams come true. (Ralph Waldo Emerson - 1850)",
  "Live in the sunshine, swim the sea, drink the wild air. (Ralph Waldo Emerson - 1845)",
  "Make the most of yourself, for that is all there is of you. (Ralph Waldo Emerson - 1841)",
  "The mind, once stretched by a new idea, never returns to its original dimensions. (Ralph Waldo Emerson - 1850)",
  "The purpose of life is not to be happy. It is to be useful, to be honorable, to be compassionate, to have it make some difference that you have lived and lived well. (Ralph Waldo Emerson - 1850)",
  "Be not the slave of your own past — plunge into the sublime seas, dive deep, and swim far. (Ralph Waldo Emerson - 1841)",
  "It is one of the blessings of old friends that you can afford to be stupid with them. (Ralph Waldo Emerson - 1841)",
  "Every artist was first an amateur. (Ralph Waldo Emerson - 1845)",
  "Write it on your heart that every day is the best day in the year. (Ralph Waldo Emerson - 1840)",
  "The sky is the daily bread of the eyes. (Ralph Waldo Emerson - 1845)",
  "Love, and you shall be loved. (Ralph Waldo Emerson - 1841)",
  "The invariable mark of wisdom is to see the miraculous in the common. (Ralph Waldo Emerson - 1840)",
  "All life is an experiment. The more experiments you make the better. (Ralph Waldo Emerson - 1841)",
  "The best way to predict the future is to create it. (Peter Drucker - 1985)",
  "Management is doing things right; leadership is doing the right things. (Peter Drucker - 1974)",
  "There is nothing so useless as doing efficiently that which should not be done at all. (Peter Drucker - 1963)",
  "The most important thing in communication is hearing what isn't said. (Peter Drucker - 1975)",
  "Efficiency is doing things right; effectiveness is doing the right things. (Peter Drucker - 1970)",
  "Knowledge has to be improved, challenged, and increased constantly, or it vanishes. (Peter Drucker - 1990)",
  "The entrepreneur always searches for change, responds to it, and exploits it as an opportunity. (Peter Drucker - 1985)",
  "We now accept the fact that learning is a lifelong process of keeping abreast of change. (Peter Drucker - 1990)",
  "Plans are only good intentions unless they immediately degenerate into hard work. (Peter Drucker - 1975)",
  "Rank does not confer privilege or give power. It imposes responsibility. (Peter Drucker - 1990)",
  "Never think that people are ever satisfied with their lot. They always want something better. (Peter Drucker - 1980)",
  "What gets measured gets managed. (Peter Drucker - 1960)",
  "You can either take action, or you can hang back and hope for a miracle. Miracles are great, but they are so unpredictable. (Peter Drucker - 1990)",
  "There is always a better way. (Thomas Edison - 1920)",
  "Genius is one percent inspiration and ninety-nine percent perspiration. (Thomas Edison - 1903)",
  "Our greatest weakness lies in giving up. The most certain way to succeed is always to try just one more time. (Thomas Edison - 1900)",
  "Opportunity is missed by most people because it is dressed in overalls and looks like work. (Thomas Edison - 1910)",
  "Many of life's failures are people who did not realize how close they were to success when they gave up. (Thomas Edison - 1905)",
  "The value of an idea lies in the using of it. (Thomas Edison - 1915)",
  "Just because something doesn't do what you planned it to do doesn't mean it's useless. (Thomas Edison - 1910)",
  "What you are will show in what you do. (Thomas Edison - 1920)",
  "To invent, you need a good imagination and a pile of junk. (Thomas Edison - 1915)",
  "Restlessness is discontent and discontent is the first necessity of progress. (Thomas Edison - 1905)",
  "There is no substitute for hard work. (Thomas Edison - 1900)",
  "The chief function of the body is to carry the brain around. (Thomas Edison - 1920)",
  "The reason a lot of people do not recognize opportunity is because it usually goes around wearing overalls looking like hard work. (Thomas Edison - 1910)",
  "Hell is empty and all the devils are here. (William Shakespeare - 1611)",
  "All the world's a stage, and all the men and women merely players. (William Shakespeare - 1599)",
  "To thine own self be true, and it must follow, as the night the day, thou canst not then be false to any man. (William Shakespeare - 1603)",
  "The course of true love never did run smooth. (William Shakespeare - 1595)",
  "Love all, trust a few, do wrong to none. (William Shakespeare - 1605)",
  "Give every man thy ear, but few thy voice. (William Shakespeare - 1603)",
  "There is nothing either good or bad, but thinking makes it so. (William Shakespeare - 1603)",
  "Cowards die many times before their deaths; The valiant never taste of death but once. (William Shakespeare - 1599)",
  "The fault, dear Brutus, is not in our stars, but in ourselves. (William Shakespeare - 1599)",
  "A fool thinks himself to be wise, but a wise man knows himself to be a fool. (William Shakespeare - 1603)",
  "We know what we are, but know not what we may be. (William Shakespeare - 1603)",
  "Better three hours too soon than a minute too late. (William Shakespeare - 1598)",
  "Expectation is the root of all heartache. (William Shakespeare - 1600)",
  "The empty vessel makes the loudest sound. (William Shakespeare - 1599)",
  "The miserable have no other medicine, but only hope. (William Shakespeare - 1604)",
  "How far that little candle throws his beams! So shines a good deed in a naughty world. (William Shakespeare - 1596)",
  "It is not in the stars to hold our destiny but in ourselves. (William Shakespeare - 1599)",
  "Our doubts are traitors, and make us lose the good we oft might win, by fearing to attempt. (William Shakespeare - 1604)",
  "Some are born great, some achieve greatness, and some have greatness thrust upon them. (William Shakespeare - 1602)",
  "I would challenge you to a battle of wits, but I see you are unarmed. (William Shakespeare - 1598)",
  "Though she be but little, she is fierce. (William Shakespeare - 1595)",
  "My words fly up, my thoughts remain below: Words without thoughts never to heaven go. (William Shakespeare - 1603)",
  "Listen to many, speak to a few. (William Shakespeare - 1603)",
  "What's done cannot be undone. (William Shakespeare - 1606)",
  "Brevity is the soul of wit. (William Shakespeare - 1603)",
  "When sorrows come, they come not single spies, but in battalions. (William Shakespeare - 1603)",
  "The robbed that smiles, steals something from the thief. (William Shakespeare - 1604)",
  "There is a tide in the affairs of men. Which, taken at the flood, leads on to fortune; Omitted, all the voyage of their life is bound in shallows and in miseries. (William Shakespeare - 1599)",
  "I wasted time, and now doth time waste me. (William Shakespeare - 1597)",
  "Have more than you show, speak less than you know. (William Shakespeare - 1606)",
  "I am in blood stepped in so far that, should I wade no more, returning were as tedious as go o'er. (William Shakespeare - 1606)",
  "Think lightly of yourself and deeply of the world. (Miyamoto Musashi - 1645)",
  "Do nothing that is of no use. (Miyamoto Musashi - 1645)",
  "You must understand that there is more than one path to the top of the mountain. (Miyamoto Musashi - 1645)",
  "The true science of martial arts means practicing them in such a way that they will be useful at any time, and to teach them in such a way that they will be useful in all things. (Miyamoto Musashi - 1645)",
  "There is nothing outside of yourself that can ever enable you to get better, stronger, richer, quicker, or smarter. Everything is within. Everything exists. Seek nothing outside of yourself. (Miyamoto Musashi - 1645)",
  "Perceive that which cannot be seen with the eye. (Miyamoto Musashi - 1645)",
  "Today is victory over yourself of yesterday; tomorrow is your victory over lesser men. (Miyamoto Musashi - 1645)",
  "The ultimate aim of martial arts is not having to use them. (Miyamoto Musashi - 1645)",
  "In battle, if you make your opponent flinch, you have already won. (Miyamoto Musashi - 1645)",
  "Respect Buddha and the gods without counting on their help. (Miyamoto Musashi - 1645)",
  "Do not seek pleasure for its own sake. (Miyamoto Musashi - 1645)",
  "Do not, under any circumstances, depend on a partial feeling. (Miyamoto Musashi - 1645)",
  "From one thing, know ten thousand things. (Miyamoto Musashi - 1645)",
  "It may seem difficult at first, but everything is difficult at first. (Miyamoto Musashi - 1645)",
  "The spirit of defeating a man is the same for ten million men. (Miyamoto Musashi - 1645)",
  "If you wish to control others you must first control yourself. (Miyamoto Musashi - 1645)",
  "Step by step walk the thousand-mile road. (Miyamoto Musashi - 1645)",
  "Truth is not what you want it to be; it is what it is. And you must bend to its power or live a lie. (Miyamoto Musashi - 1645)",
  "No man is invincible, and therefore no man can fully understand that which would make him invincible. (Miyamoto Musashi - 1645)",
  "You can only fight the way you practice. (Miyamoto Musashi - 1645)",
  "The only reason a warrior is alive is to fight, and the only reason a warrior fights is to win. (Miyamoto Musashi - 1645)",
  "Study strategy over the years and achieve the spirit of the warrior. Today is victory over yourself of yesterday. (Miyamoto Musashi - 1645)",
  "Know your enemy, know his sword. (Miyamoto Musashi - 1645)",
  "To know ten thousand things, know one well. (Miyamoto Musashi - 1645)",
  "The field of martial arts is particularly rife with flamboyant showmanship. (Miyamoto Musashi - 1645)",
  "The best time to plant a tree was twenty years ago. The second best time is now. (Chinese Proverb - Unknown)",
  "A journey of a thousand miles must begin with a single step. (Chinese Proverb - Unknown)",
  "Teachers open the door, but you must enter by yourself. (Chinese Proverb - Unknown)",
  "He who asks a question is a fool for five minutes; he who does not ask remains a fool forever. (Chinese Proverb - Unknown)",
  "Dig the well before you are thirsty. (Chinese Proverb - Unknown)",
  "Talk does not cook rice. (Chinese Proverb - Unknown)",
  "Be not afraid of growing slowly; be afraid only of standing still. (Chinese Proverb - Unknown)",
  "A book holds a house of gold. (Chinese Proverb - Unknown)",
  "The person who says it cannot be done should not interrupt the person doing it. (Chinese Proverb - Unknown)",
  "A diamond with a flaw is worth more than a pebble without imperfections. (Chinese Proverb - Unknown)",
  "To know the road ahead, ask those coming back. (Chinese Proverb - Unknown)",
  "An invisible thread connects those who are destined to meet, regardless of time, place, and circumstance. (Chinese Proverb - Unknown)",
  "If you are patient in one moment of anger, you will escape a hundred days of sorrow. (Chinese Proverb - Unknown)",
  "Better a diamond with a flaw than a pebble without one. (Chinese Proverb - Unknown)",
  "A bird does not sing because it has an answer. It sings because it has a song. (Chinese Proverb - Unknown)",
  "The palest ink is better than the best memory. (Chinese Proverb - Unknown)",
  "Pearls don't lie on the seashore. If you want one, you must dive for it. (Chinese Proverb - Unknown)",
  "A child's life is like a piece of paper on which every person leaves a mark. (Chinese Proverb - Unknown)",
  "When the winds of change blow, some people build walls and others build windmills. (Chinese Proverb - Unknown)",
  "A single conversation with a wise man is better than ten years of study. (Chinese Proverb - Unknown)",
  "The wolf has a winning game when the shepherds quarrel. (Chinese Proverb - Unknown)",
  "One moment of patience may ward off great disaster. (Chinese Proverb - Unknown)",
  "A nation's treasure is in its scholars. (Chinese Proverb - Unknown)",
  "I hear and I forget. I see and I remember. I do and I understand. (Chinese Proverb - Unknown)",
  "Do not confine your children to your own learning, for they were born in another time. (Chinese Proverb - Unknown)",
  "This too shall pass. (Persian Proverb - Unknown)",
  "When fate strikes, physicians are useless. (Persian Proverb - Unknown)",
  "The wise man sits on the hole in his carpet. (Persian Proverb - Unknown)",
  "I cried because I had no shoes until I met a man who had no feet. (Persian Proverb - Unknown)",
  "A loose tooth will not rest until it is pulled out. (Persian Proverb - Unknown)",
  "Anger begins with folly and ends with repentance. (Persian Proverb - Unknown)",
  "He who has been bitten by a snake fears a piece of string. (Persian Proverb - Unknown)",
  "The ocean does not become dirty because a dog drinks from it. (Persian Proverb - Unknown)",
  "Little by little, the camel goes into the couscous. (Persian Proverb - Unknown)",
  "Even a lion has to defend himself against flies. (Persian Proverb - Unknown)",
  "The best memory is weaker than the palest ink. (Persian Proverb - Unknown)",
  "When the cat and mouse agree, the grocer is ruined. (Persian Proverb - Unknown)",
  "A mad man drops a rock into the well, so that forty wise men cannot get it out. (Persian Proverb - Unknown)",
  "Do not cut down the tree that gives you shade. (Persian Proverb - Unknown)",
  "He who wants a rose must respect the thorn. (Persian Proverb - Unknown)",
  "The night hides a world, but reveals a universe. (Persian Proverb - Unknown)",
  "Time is a river, and books are boats. (Persian Proverb - Unknown)",
  "There are a thousand ways to kneel and kiss the ground; there is only one way to fly. (Persian Proverb - Unknown)",
  "A gentle hand may lead even an elephant by a hair. (Persian Proverb - Unknown)",
  "The wound of a sword heals, but the wound of the tongue does not. (Persian Proverb - Unknown)",
  "Risk the sea to gain the pearl. (Persian Proverb - Unknown)",
  "If the mountain does not come to you, you must go to the mountain. (Persian Proverb - Unknown)",
  "A stone thrown into a friend's garden is a flower thrown into an enemy's courtyard. (Persian Proverb - Unknown)",
  "Luck is when preparation meets opportunity. (Persian Proverb - Unknown)",
  "Four things come not back: the spoken word, the sped arrow, the past life, and the neglected opportunity. (Arabian Nights Proverb - 800 AD)",
  "He who has health has hope; and he who has hope, has everything. (Arabian Nights Proverb - 800 AD)",
  "The fool tells me his business, the wise man hides it even from himself. (Arabian Nights Proverb - 800 AD)",
  "No man is born into this world without having been destroyed a thousand times. (Arabian Nights Proverb - 800 AD)",
  "The life of man is a journey that must be taken, no matter how bad the roads and accommodations. (Arabian Nights Proverb - 800 AD)",
  "A secret is like a dove: when it leaves my hand it takes wing. (Arabian Nights Proverb - 800 AD)",
  "He who peeps at the neighbor's window may chance to lose his eyes. (Arabian Nights Proverb - 800 AD)",
  "Trust in God, but tie your camel. (Arabian Nights Proverb - 800 AD)",
  "The best speech is that which is short and to the point. (Arabian Nights Proverb - 800 AD)",
  "Every sun must set. (Arabian Nights Proverb - 800 AD)",
  "A friend is known in the time of need. (Arabian Nights Proverb - 800 AD)",
  "The greatest wealth is wisdom. (Arabian Nights Proverb - 800 AD)",
  "The tongue of experience utters the most. (Arabian Nights Proverb - 800 AD)",
  "Patience is the key to relief. (Arabian Nights Proverb - 800 AD)",
  "A wise man first thinks and then speaks, and a fool speaks first and then thinks. (Arabian Nights Proverb - 800 AD)",
  "The envious person is the unhappiest. (Arabian Nights Proverb - 800 AD)",
  "He who digs a pit for his brother falls into it. (Arabian Nights Proverb - 800 AD)",
  "Every day of your life is a page of your history. (Arabian Nights Proverb - 800 AD)",
  "If it is to be, it is up to me. (Arabian Nights Proverb - 800 AD)",
  "The soul is healed by being with children. (Arabian Nights Proverb - 800 AD)",
  "Parting is the twin-brother of death. (Arabian Nights Proverb - 800 AD)",
  "Love makes the impossible possible. (Arabian Nights Proverb - 800 AD)",
  "Words are the ships that sail across the sea of thought. (Arabian Nights Proverb - 800 AD)",
  "A house divided against itself cannot stand. (Arabian Nights Proverb - 800 AD)",
  "The best richness is the richness of the soul. (Arabian Nights Proverb - 800 AD)",
  "Do not be deceived by the beauty of the morning; wait for the sunset. (Arabian Nights Proverb - 800 AD)",
  "What is the point of being a bird, thought the Wart, if you have to be a bird in a cage? (T.H. White - The Sword in the Stone)",
  "The moment you doubt whether you can fly, you cease forever to be able to do it. (J.M. Barrie - Peter Pan)",
  "To die will be an awfully big adventure. (J.M. Barrie - Peter Pan)",
  "Dreams do come true, if only we wish hard enough. (J.M. Barrie - Peter Pan)",
  "Second star to the right and straight on till morning. (J.M. Barrie - Peter Pan)",
  "It is not our abilities that show what we truly are. It is our choices. (J.K. Rowling - Harry Potter)",
  "Happiness can be found, even in the darkest of times, if one only remembers to turn on the light. (J.K. Rowling - Harry Potter)",
  "Words are, in my not-so-humble opinion, our most inexhaustible source of magic. (J.K. Rowling - Harry Potter)",
  "It is a truth universally acknowledged that a single man in possession of a good fortune, must be in want of a wife. Not all truths, however, are kind. (Jane Austen - Pride and Prejudice)",
  "The person, be it gentleman or lady, who has not pleasure in a good novel, must be intolerably stupid. (Jane Austen - Northanger Abbey)",
  "It isn't what we say or think that defines us, but what we do. (Jane Austen - Sense and Sensibility)",
  "I do not want people to be very agreeable, as it saves me the trouble of liking them a great deal. (Jane Austen - Letters)",
  "How quick come the reasons for approving what we like. (Jane Austen - Persuasion)",
  "I must learn to be content with being happier than I deserve. (Jane Austen - Pride and Prejudice)",
  "One cannot be brave who has no fear. (L. Frank Baum - The Wizard of Oz)",
  "A heart is not judged by how much you love, but by how much you are loved by others. (L. Frank Baum - The Wizard of Oz)",
  "There is no place like home. (L. Frank Baum - The Wizard of Oz)",
  "Some people without brains do an awful lot of talking. (L. Frank Baum - The Wizard of Oz)",
  "Everything has to come to an end, sometime. (L. Frank Baum - The Wizard of Oz)",
  "'What is the use of a book', thought Alice, 'without pictures or conversation?' (Lewis Carroll - Alice in Wonderland)",
  "I can't go back to yesterday because I was a different person then. (Lewis Carroll - Alice in Wonderland)",
  "If you don't know where you are going, any road will get you there. (Lewis Carroll - Alice in Wonderland)",
  "Who in the world am I? Ah, that's the great puzzle. (Lewis Carroll - Alice in Wonderland)",
  "Why, sometimes I've believed as many as six impossible things before breakfast. (Lewis Carroll - Alice in Wonderland)",
  "Everything's got a moral, if only you can find it. (Lewis Carroll - Alice in Wonderland)",
  "We're all mad here. (Lewis Carroll - Alice in Wonderland)",
  "One of the deep secrets of life is that all that is really worth doing is what we do for others. (Lewis Carroll - 1890)",
  "It's no use going back to yesterday, because I was a different person then. (Lewis Carroll - Alice in Wonderland)",
  "Imagination is the only weapon in the war against reality. (Lewis Carroll - Alice in Wonderland)",
  "No act of kindness, no matter how small, is ever wasted. (Aesop - 600 BC)",
  "Slow and steady wins the race. (Aesop - 600 BC)",
  "It is easy to be brave from a safe distance. (Aesop - 600 BC)",
  "The smaller the mind, the greater the conceit. (Aesop - 600 BC)",
  "We often give our enemies the means for our own destruction. (Aesop - 600 BC)",
  "Appearances are often deceiving. (Aesop - 600 BC)",
  "United we stand, divided we fall. (Aesop - 600 BC)",
  "Beware that you do not lose the substance by grasping at the shadow. (Aesop - 600 BC)",
  "Please all, and you will please none. (Aesop - 600 BC)",
  "Better be wise by the misfortunes of others than by your own. (Aesop - 600 BC)",
  "Those who seek to please everybody please nobody. (Aesop - 600 BC)",
  "The fly sat upon the axle-tree of the chariot-wheel and said, 'What a dust do I raise!' (Aesop - 600 BC)",
  "Be content with your lot; one cannot be first in everything. (Aesop - 600 BC)",
  "It is wise to turn circumstances to good account. (Aesop - 600 BC)",
  "In union there is strength. (Aesop - 600 BC)",
  "Self-conceit may lead to self-destruction. (Aesop - 600 BC)",
  "After all is said and done, more is said than done. (Aesop - 600 BC)",
  "Little by little does the trick. (Aesop - 600 BC)",
  "The level of our success is limited only by our imagination. (Aesop - 600 BC)",
  "A liar will not be believed, even when he speaks the truth. (Aesop - 600 BC)",
  "It is not death that a man should fear, but he should fear never beginning to live. (Epictetus - 100 AD)",
  "First say to yourself what you would be; and then do what you have to do. (Epictetus - 100 AD)",
  "Men are disturbed not by things, but by the view which they take of them. (Epictetus - 100 AD)",
  "Wealth consists not in having great possessions, but in having few wants. (Epictetus - 100 AD)",
  "No man is free who is not master of himself. (Epictetus - 100 AD)",
  "If you want to improve, be content to be thought foolish and stupid. (Epictetus - 100 AD)",
  "Don't explain your philosophy. Embody it. (Epictetus - 100 AD)",
  "The key is to keep company only with people who uplift you. (Epictetus - 100 AD)",
  "How long are you going to wait before you demand the best for yourself? (Epictetus - 100 AD)",
  "Circumstances don't make the man, they only reveal him to himself. (Epictetus - 100 AD)",
  "It's not what happens to you, but how you react to it that matters. (Epictetus - 100 AD)",
  "Nature has given to men one tongue, but two ears, that we may hear from others twice as much as we speak. (Epictetus - 100 AD)",
  "Make the best use of what is in your power, and take the rest as it happens. (Epictetus - 100 AD)",
  "To accuse others for one's own misfortunes is a sign of want of education. To accuse oneself shows that one's education has begun. To accuse neither oneself nor others shows that one's education is complete. (Epictetus - 100 AD)",
  "He is a wise man who does not grieve for the things which he has not, but rejoices for those which he has. (Epictetus - 100 AD)",
  "Keep silence for the most part, and speak only when you must. (Epictetus - 100 AD)",
  "If anyone tells you that a certain person speaks ill of you, do not make excuses about what is said of you but answer, 'He was ignorant of my other faults, else he would not have mentioned these alone.' (Epictetus - 100 AD)",
  "Difficulty shows what men are. (Epictetus - 100 AD)",
  "Freedom is the only worthy goal in life. It is won by disregarding things that lie beyond our control. (Epictetus - 100 AD)",
  "The greater the difficulty, the more glory in surmounting it. (Epictetus - 100 AD)",
  "We have two ears and one mouth so that we can listen twice as much as we speak. (Epictetus - 100 AD)",
  "Man is troubled not by events, but by the meaning he gives them. (Epictetus - 100 AD)",
  "Suffering arises from trying to control what is uncontrollable, or from neglecting what is within our power. (Epictetus - 100 AD)",
  "Of all people only those are at leisure who make time for philosophy, only those are really alive. (Seneca - 50 AD)",
  "We suffer more often in imagination than in reality. (Seneca - 55 AD)",
  "Luck is what happens when preparation meets opportunity. (Seneca - 60 AD)",
  "It is not that we have a short time to live, but that we waste a lot of it. (Seneca - 50 AD)",
  "He who is brave is free. (Seneca - 55 AD)",
  "He who is everywhere is nowhere. (Seneca - 60 AD)",
  "A gem cannot be polished without friction, nor a man perfected without trials. (Seneca - 55 AD)",
  "Difficulties strengthen the mind, as labor does the body. (Seneca - 50 AD)",
  "If a man knows not to which port he sails, no wind is favorable. (Seneca - 55 AD)",
  "Wealth is the slave of a wise man. The master of a fool. (Seneca - 60 AD)",
  "All cruelty springs from weakness. (Seneca - 55 AD)",
  "The whole future lies in uncertainty: live immediately. (Seneca - 50 AD)",
  "Only time can heal what reason cannot. (Seneca - 60 AD)",
  "It is the power of the mind to be unconquerable. (Seneca - 55 AD)",
  "No man was ever wise by chance. (Seneca - 50 AD)",
  "Begin at once to live, and count each separate day as a separate life. (Seneca - 55 AD)",
  "It is a rough road that leads to the heights of greatness. (Seneca - 60 AD)",
  "The greatest remedy for anger is delay. (Seneca - 55 AD)",
  "Life is long, if you know how to use it. (Seneca - 50 AD)",
  "To be everywhere is to be nowhere. (Seneca - 60 AD)",
  "The sun also shines on the wicked. (Seneca - 55 AD)",
  "Stand a little less between me and the sun. (Diogenes - 350 BC)",
  "I am looking for an honest man. (Diogenes - 350 BC)",
  "The foundation of every state is the education of its youth. (Diogenes - 350 BC)",
  "It is the privilege of the gods to want nothing, and of godlike men to want little. (Diogenes - 350 BC)",
  "I know nothing, except the fact of my ignorance. (Diogenes - 350 BC)",
  "The art of being a slave is to rule one's master. (Diogenes - 350 BC)",
  "As a matter of self-preservation, a man needs good friends or ardent enemies, for the former instruct him and the latter take him to task. (Diogenes - 350 BC)",
  "The wise man knows that he knows nothing; the fool thinks he knows everything. (Diogenes - 350 BC)",
  "I like thinking big. If you're going to be thinking anything, you might as well think big. (Donald Trump - 1987)",
  "Sometimes by losing a battle you find a new way to win the war. (Donald Trump - 2004)",
  "What separates the winners from the losers is how a person reacts to each new twist of fate. (Donald Trump - 2004)",
  "As long as you're going to be thinking anyway, think big. (Donald Trump - 1987)",
  "You have to think anyway, so why not think big? (Donald Trump - 1987)",
  "In the end, you're measured not by how much you undertake but by what you finally accomplish. (Donald Trump - 2004)",
  "Experience taught me a few things. One is to listen to your gut, no matter how good something sounds on paper. (Donald Trump - 2004)",
  "Everything in life is luck. (Donald Trump - 2015)",
  "Show me someone without an ego, and I'll show you a loser. (Donald Trump - 2004)",
  "If you're interested in 'balancing' work and pleasure, stop trying to balance them. Instead make your work more pleasurable. (Donald Trump - 2004)",
  "Educating the mind without educating the heart is no education at all. (Aristotle - 340 BC)",
  "Knowing yourself is the beginning of all wisdom. (Aristotle - 340 BC)",
  "It is the mark of an educated mind to be able to entertain a thought without accepting it. (Aristotle - 340 BC)",
  "The whole is greater than the sum of its parts. (Aristotle - 340 BC)",
  "No great mind has ever existed without a touch of madness. (Aristotle - 340 BC)",
  "Happiness depends upon ourselves. (Aristotle - 340 BC)",
  "The roots of education are bitter, but the fruit is sweet. (Aristotle - 340 BC)",
  "Patience is bitter, but its fruit is sweet. (Aristotle - 340 BC)",
  "The energy of the mind is the essence of life. (Aristotle - 340 BC)",
  "Friendship is a single soul dwelling in two bodies. (Aristotle - 340 BC)",
  "He who is unable to live in society, or who has no need because he is sufficient for himself, must be either a beast or a god. (Aristotle - 340 BC)",
  "The more you know, the more you know you don't know. (Aristotle - 340 BC)",
  "Courage is the first of human qualities because it is the quality which guarantees the others. (Aristotle - 340 BC)",
  "The aim of the wise is not to secure pleasure, but to avoid pain. (Aristotle - 340 BC)",
  "Wise men speak because they have something to say; fools because they have to say something. (Plato - 360 BC)",
  "Be kind, for everyone you meet is fighting a harder battle. (Plato - 360 BC)",
  "We can easily forgive a child who is afraid of the dark; the real tragedy of life is when men are afraid of the light. (Plato - 360 BC)",
  "Only the dead have seen the end of war. (Plato - 360 BC)",
  "The measure of a man is what he does with power. (Plato - 360 BC)",
  "Good people do not need laws to tell them to act responsibly, while bad people will find a way around the laws. (Plato - 360 BC)",
  "Music gives a soul to the universe, wings to the mind, flight to the imagination, and life to everything. (Plato - 360 BC)",
  "I am the wisest man alive, for I know one thing, and that is that I know nothing. (Plato - 360 BC)",
  "There is truth in wine and children. (Plato - 360 BC)",
  "The beginning is the most important part of the work. (Plato - 360 BC)",
  "Those who tell the stories rule society. (Plato - 360 BC)",
  "An empty vessel makes the loudest sound, so they that have the least wit are the greatest babblers. (Plato - 360 BC)",
  "No one is more hated than he who speaks the truth. (Plato - 360 BC)",
  "Necessity is the mother of invention. (Plato - 360 BC)",
  "A house that has a library in it has a soul. (Plato - 360 BC)",
  "The soul takes nothing with her to the next world but her education and her culture. (Plato - 360 BC)",
  "Let him that would move the world first move himself. (Socrates - 399 BC)",
  "Be as you wish to seem. (Socrates - 399 BC)",
  "The only good is knowledge and the only evil is ignorance. (Socrates - 399 BC)",
  "I cannot teach anybody anything. I can only make them think. (Socrates - 399 BC)",
  "Be slow to fall into friendship, but when you are in, continue firm and constant. (Socrates - 399 BC)",
  "To find yourself, think for yourself. (Socrates - 399 BC)",
  "He who is not contented with what he has, would not be contented with what he would like to have. (Socrates - 399 BC)",
  "The secret of happiness, you see, is not found in seeking more, but in developing the capacity to enjoy less. (Socrates - 399 BC)",
  "False words are not only evil in themselves, but they infect the soul with evil. (Socrates - 399 BC)",
  "Beware the barrenness of a busy life. (Socrates - 399 BC)",
  "Death may be the greatest of all human blessings. (Socrates - 399 BC)",
  "By all means, marry. If you get a good wife, you'll become happy; if you get a bad one, you'll become a philosopher. (Socrates - 399 BC)",
  "The hottest love has the coldest end. (Socrates - 399 BC)",
  "An honest man is always a child. (Socrates - 399 BC)",
  "Think not those faithful who praise all your words and actions; but those who kindly reprove your faults. (Socrates - 399 BC)",
  "Judge a man by his questions rather than his answers. (Voltaire - 1765)",
  "Common sense is not so common. (Voltaire - 1764)",
  "It is difficult to free fools from the chains they revere. (Voltaire - 1765)",
  "The more I read, the more I acquire, the more certain I am that I know nothing. (Voltaire - 1765)",
  "No snowflake in an avalanche ever feels responsible. (Voltaire - 1760)",
  "It is better to risk saving a guilty person than to condemn an innocent one. (Voltaire - 1765)",
  "Despite the enormous quantity of books, how few people read! And if one reads profitably, one would realize how much stupid stuff the vulgar herd is content to swallow every day. (Voltaire - 1765)",
  "The art of medicine consists in amusing the patient while nature cures the disease. (Voltaire - 1760)",
  "Appreciation is a wonderful thing: It makes what is excellent in others belong to us as well. (Voltaire - 1765)",
  "The longer we dwell on our misfortunes, the greater is their power to harm us. (Voltaire - 1760)",
  "Say what you will to a man, he will only hear what he wants to hear. (Voltaire - 1765)",
  "Life is a shipwreck, but we must not forget to sing in the lifeboats. (Voltaire - 1760)",
  "Let us read, and let us dance; these two amusements will never do any harm to the world. (Voltaire - 1765)",
  "Superstition is to religion what astrology is to astronomy: the mad daughter of a wise mother. (Voltaire - 1760)",
  "The only way to comprehend what mathematicians mean by Infinity is to contemplate the extent of human stupidity. (Voltaire - 1765)",
  "The secret of being a bore is to tell everything. (Voltaire - 1760)",
  "Ice cream is exquisite. What a pity it isn't illegal. (Voltaire - 1765)",
  "If God did not exist, it would be necessary to invent him. (Voltaire - 1765)",
  "Those who can make you believe absurdities can make you commit atrocities. (Voltaire - 1765)",
  "Violence is the last refuge of the incompetent. (Isaac Asimov - 1951)",
  "The saddest aspect of life right now is that science gathers knowledge faster than society gathers wisdom. (Isaac Asimov - 1988)",
  "People think of education as something they can finish. (Isaac Asimov - 1985)",
  "In life, unlike chess, the game continues after checkmate. (Isaac Asimov - 1960)",
  "Self-education is, I firmly believe, the only kind of education there is. (Isaac Asimov - 1975)",
  "The most exciting phrase to hear in science, the one that heralds new discoveries, is not 'Eureka!' but 'That's funny...' (Isaac Asimov - 1970)",
  "Never let your sense of morals prevent you from doing what is right. (Isaac Asimov - 1942)",
  "If knowledge can create problems, it is not through ignorance that we can solve them. (Isaac Asimov - 1970)",
  "Life is pleasant. Death is peaceful. It's the transition that's troublesome. (Isaac Asimov - 1980)",
  "To succeed, planning alone is insufficient. One must improvise as well. (Isaac Asimov - 1952)",
  "There is no belief, however foolish, that will not gather its faithful adherents who will defend it to the death. (Isaac Asimov - 1980)",
  "The strain of anti-intellectualism has been a constant thread winding its way through our political and cultural life. (Isaac Asimov - 1980)",
  "It has been my philosophy of life that difficulties vanish when faced boldly. (Isaac Asimov - 1960)",
  "Better make a weak man think he is strong than a strong man think he is weak. (Homer - 750 BC)",
  "There is a time for many words, and there is also a time for sleep. (Homer - 750 BC)",
  "A man who has been through bitter experiences and travelled far enjoys even his sufferings after a time. (Homer - 750 BC)",
  "The gods envy us. They envy us because we're mortal, because any moment might be our last. Everything is more beautiful because we're doomed. (Homer - 750 BC)",
  "Of all creatures that breathe and move upon the earth, nothing is bred that is weaker than man. (Homer - 750 BC)",
  "Hateful to me as the gates of Hades is that man who hides one thing in his heart and speaks another. (Homer - 750 BC)",
  "Even a fool learns something once it hits him. (Homer - 750 BC)",
  "The journey is the thing. (Homer - 750 BC)",
  "Yet, taught by time, my heart has learned to glow for others' good, and melt at others' woe. (Homer - 750 BC)",
  "There is nothing more majestic than the human spirit, nothing more admirable than its courage in the face of overwhelming odds. (Homer - 750 BC)",
  "Let me not then die ingloriously and without a struggle, but let me first do some great thing that shall be told among men hereafter. (Homer - 750 BC)",
  "For a friend with an understanding heart is worth no less than a brother. (Homer - 750 BC)",
  "Everything is more beautiful because we are doomed. (Homer - 750 BC)",
  "The blade itself incites to deeds of violence. (Homer - 750 BC)",
];

function getQuote(): string {
  return quotes[Math.floor(Math.random() * quotes.length)];
}

export default function (pi: ExtensionAPI) {
  pi.on("turn_start", async (_event, ctx) => {
    ctx.ui.setWorkingMessage(getQuote());
  });

  pi.on("turn_end", async (_event, ctx) => {
    ctx.ui.setWorkingMessage();
  });
}
